# Generated by Django 3.0.8 on 2020-07-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
