# Generated by Django 3.0.8 on 2020-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to='question_images'),
            preserve_default=False,
        ),
    ]
